# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Verikt < Formula
  desc "Your architecture, in every agent session"
  homepage "https://github.com/diktahq/verikt"
  version "0.1.0"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/diktahq/verikt/releases/download/v0.1.0/verikt_0.1.0_darwin_amd64.tar.gz"
      sha256 "7546597eb8d7932af91ccd04af6cf7b513ec2cf5b00b2b57714eb1c403b86f79"

      define_method(:install) do
        bin.install "verikt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/diktahq/verikt/releases/download/v0.1.0/verikt_0.1.0_darwin_arm64.tar.gz"
      sha256 "7ab37725d5f1a4dca7e8da0172854e6d425d47e2d7d60857e831ef4e38cc5768"

      define_method(:install) do
        bin.install "verikt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/diktahq/verikt/releases/download/v0.1.0/verikt_0.1.0_linux_amd64.tar.gz"
      sha256 "0332f63da445a4788d7945b287e03fe4a003bbb21a42517ab2a59456aba1a08e"
      define_method(:install) do
        bin.install "verikt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/diktahq/verikt/releases/download/v0.1.0/verikt_0.1.0_linux_arm64.tar.gz"
      sha256 "d527981ff58adc6988fe9fc1985f85a95c9b5f27699a6b40909a54c458d18605"
      define_method(:install) do
        bin.install "verikt"
      end
    end
  end

  def post_install
    system "#{bin}/verikt", "setup"
  end

  test do
    system "#{bin}/verikt", "version"
  end
end
