# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Verikt < Formula
  desc "Your architecture, in every agent session"
  homepage "https://github.com/diktahq/verikt"
  version "0.2.0"
  license "Elastic-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/diktahq/verikt/releases/download/v0.2.0/verikt_0.2.0_darwin_amd64.tar.gz"
      sha256 "c7b48db359fe830d1cdc0121de09d2236e4763d32211a52e92cef16cfd0c8590"

      define_method(:install) do
        bin.install "verikt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/diktahq/verikt/releases/download/v0.2.0/verikt_0.2.0_darwin_arm64.tar.gz"
      sha256 "5f927e241bd219fbc097d40f3369727cfc3a0d2d9eea94e4240f86e60e1c7b1a"

      define_method(:install) do
        bin.install "verikt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/diktahq/verikt/releases/download/v0.2.0/verikt_0.2.0_linux_amd64.tar.gz"
      sha256 "17559add01ee48ef34f4f8e85b38aa021d1047808ea6c808ed8c4a509866ef12"
      define_method(:install) do
        bin.install "verikt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/diktahq/verikt/releases/download/v0.2.0/verikt_0.2.0_linux_arm64.tar.gz"
      sha256 "bc62db7758a63a7fe60fbbf712b1b9ac34834507680cc0bc2171fe2d6c4098fb"
      define_method(:install) do
        bin.install "verikt"
      end
    end
  end

  def post_install
    system "#{bin}/verikt", "setup"
  end

  test do
    system "#{bin}/verikt", "version"
  end
end
